#!/usr/bin/env python3
"""Emit the C source for ov039's .data string objects.

Reads the dsd disassembly, so the Shift-JIS bytes come from the ROM rather than
being retyped.  Objects are emitted in the order the target lays them out, which
is the order they appear in the disassembly -- mwcc sorts by size ascending and
ties break by a heapsort over creation order, so the sequence here is the
creation order the original source used, not something to re-derive.

    python tools/ov039_strgen.py            # -> print C
    python tools/ov039_strgen.py -o out.c    # -> write file
"""
import argparse
import re
import sys

ASM = "build/usa/asm/ov039_4.s"
LO, HI = 0x0209A14C, 0x0209A2E0
# The strings are the only part of the .data range that tools/ov039_strgen.py
# generates; tools/ov039_datagen.py prepends the rest.


def parse_region():
    txt = open(ASM, errors="replace").read()
    start = txt.index(f"data_ov039_{LO:08x}:")
    end = txt.index(f"data_ov039_{HI:08x}:")
    seg = txt[start:end]
    out = []
    for m in re.finditer(
            r"^(data_ov039_\w+):( ; ambiguous)?\n((?:    \.byte [^\n]*\n)+)",
            seg, re.M):
        name = m.group(1)
        raw = bytes(int(x, 16) for x in
                    re.findall(r"0x([0-9a-fA-F]{2})", m.group(3)))
        out.append((name, raw))
    return out


# The three single-character glyphs at the head of the string block are the
# result screens' scrollbar markers, drawn by func_ov039_02083bb0. They are
# worth naming: the code references them individually by address, and
# Otu_str_0209a16c says nothing about what they are.
GLYPH_NAMES = {
    "data_ov039_0209a16c": "OtuGlyph_ScrollFill",
    "data_ov039_0209a170": "OtuGlyph_ScrollDot",
    "data_ov039_0209a174": "OtuGlyph_ScrollHead",
}


def c_identifier(name):
    """data_ov039_0209a188 -> Otu_str_0209a188"""
    if name in GLYPH_NAMES:
        return GLYPH_NAMES[name]
    return "Otu_str_" + name.split("_")[-1]


def emit(objs):
    lines = [
        "/*",
        " * Otosu menu labels and separators.",
        " *",
        " * Generated by tools/ov039_strgen.py from build/usa/asm/ov039_4.s -- the",
        " * Shift-JIS bodies come straight from the ROM, so do not hand-edit them;",
        " * the build compiles this file with -enc SJIS.",
        " *",
        " * These are the three Otosu result-screen menus (SINGLE MENU 1/2/3).",
        " * func_ov039_02086174 picks a menu by index and draws its rows;",
        " * func_ov039_02083bb0 draws the two-value scrollbar using the separator",
        " * glyphs below.",
        " *",
        " * Order matters: mwcc sorts .data objects by size ascending and breaks ties",
        " * with a heapsort over creation order, so this sequence is load-bearing.",
        " */",
        "",
    ]
    for name, raw in objs:
        ident = c_identifier(name)
        body = raw.split(b"\x00")[0]
        lines.append(f"/* {ident}: {len(raw)} bytes at {name} */")
        if not body:
            lines.append(f"const char {ident}[{len(raw)}] = {{0}};")
            lines.append("")
            continue
        try:
            body.decode("shift_jis")
        except UnicodeDecodeError:
            print(f"!! {name} is not valid Shift-JIS: {body.hex()}", file=sys.stderr)
            return None
        # mwcc rejects "\0" style escapes inside a string initialiser, so emit
        # an explicit byte array.  A bare char array is also what keeps the
        # object's size equal to the target's, which is the sort key mwcc uses.
        vals = ", ".join(str(b) for b in raw)
        if len(vals) > 88:
            vals = "\n    " + ",\n    ".join(
                ", ".join(str(b) for b in raw[i:i + 12])
                for i in range(0, len(raw), 12)
            ).replace("\n", "\n    ") + "\n"
        lines.append(f"const char {ident}[{len(raw)}] = {{{vals}}};")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", required=True,
                    help="destination .c path (written as Shift-JIS)")
    a = ap.parse_args()
    src = emit(parse_region())
    if src is None:
        sys.exit(1)
    # The build compiles with -enc SJIS, so the file must BE Shift-JIS.  Writing
    # it as UTF-8 would mangle every multi-byte kana/kanji on the way in.
    open(a.output, "w", encoding="shift_jis", errors="replace").write(src)
    print(f"wrote {a.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
