#!/usr/bin/env python3
"""Emit a decomp-permuter `target.s` for one ov039 function.

The upstream prelude.inc is MIPS-flavoured (`.set noat`), and this repo's
disassembly calls out to functions in other overlays that have no local label.
Both need handling before arm-none-eabi-as will accept the file:

  * the `.set noat` / `.set noreorder` / `.set gp=64` lines are dropped; they are
    MIPS directives and arm-none-eabi-as rejects them;
  * every symbol referenced but not defined in the function gets an absolute
    stub at the end, so `bl`/`ldr` pool references resolve. Their addresses are
    irrelevant -- the permuter only diffs this function's own bytes.

    python tools/perm_target.py <function> [asm-file]
"""

import re
import sys
from pathlib import Path

ASM = "build/usa/asm/ov039_4.s"
OUT = Path("nonmatchings")


def main():
    func = sys.argv[1]
    asm_path = sys.argv[2] if len(sys.argv) > 2 else ASM
    text = Path(asm_path).read_text(encoding="latin1")

    m = re.search(rf"_func_start {func}\n(.*?)(?:arm|thumb)_func_end {func}", text, re.S)
    if not m:
        sys.exit(f"{func} not found in {asm_path}")
    lines = m.group(1).split("\n")
    lines[0] = lines[0].split(" ; ")[0]
    # The disassembly annotates with trailing `;` comments in two places, and
    # arm-none-eabi-as parses both as part of the operand rather than as
    # comments: on instructions (`bl foo ; bar`) and on label lines
    # (`.L_x: ; jump table`).
    def strip(ln):
        if re.match(r"^\s*(\.\w+:)\s*;", ln):
            return re.match(r"^\s*\.\w+:", ln).group(0)
        if re.match(r"^\s*[a-z]", ln):
            return re.sub(r"\s*;.*$", "", ln)
        return ln

    body = "\n".join(strip(ln) for ln in lines)

    # Symbols this function defines: labels, and pool entries of the form
    # `.L_x: .word some_sym`.
    defined = set(re.findall(r"^(\w+):", body, re.M))
    defined |= {
        ref
        for ref in re.findall(r"^\.L_\w+:\s*\.word\s+(\w+)", body, re.M)
    }
    defined |= {func}

    referenced = set(re.findall(r"^\s*(?:bl|b)\s+(\w+)", body, re.M))
    referenced |= set(re.findall(r"^\.L_\w+:\s*\.word\s+([\w@.]+)", body, re.M))

    external = sorted(
        s
        for s in referenced
        if s not in defined and not s.startswith(".L_") and re.fullmatch(r"\w+", s)
    )

    stub = "\n" + "\n".join(
        f".globl {s}\n{s}:\n.word 0" for s in external
    )

    out = (
        f"// Generated by tools/perm_target.py for {func}.\n"
        f"// {len(external)} external symbol(s) stubbed with placeholder addresses.\n"
        ".syntax unified\n.text\n.arm\n"
        f".globl {func}\n.type {func}, %function\n"
        + body
        + f"\n.size {func}, .-{func}\n"
        + stub + "\n"
    )

    d = OUT / func
    d.mkdir(parents=True, exist_ok=True)
    (d / "target.s").write_text(out)
    print(f"{func}: target.s {len(out)} bytes, {len(external)} externals stubbed")
    if external:
        print("  " + ", ".join(external[:8]) + (" ..." if len(external) > 8 else ""))


if __name__ == "__main__":
    main()
